# Generated by Django 3.1.4 on 2020-12-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
